- hosts: all
  tasks:
  - name: Install apache
    package:
      name: "{{ package }}"
      state: present

  - name: Start Apache
    systemd:
      state: started
      enabled: yes
      name: "{{ service }}" 

  - name: Download Template
    get_url:
      url: https://www.free-css.com/assets/files/free-css-templates/download/page296/finexo.zip
      dest: /tmp/finexo.zip

  - name: Install unzip
    package:
      name: unzip
      state: present

  - name: Extract Template
    unarchive:
      src: /tmp/finexo.zip
      dest: /tmp/
      remote_src: yes 

  - shell: mv /tmp/finexo-html/* /var/www/html/
    args:
      creates: /var/www/html/about.html